# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

col_mins_id_cpp <- function(X) {
    .Call('_ArchRCells_col_mins_id_cpp', PACKAGE = 'ArchRCells', X)
}

sp_col_mins_id_cpp <- function(X) {
    .Call('_ArchRCells_sp_col_mins_id_cpp', PACKAGE = 'ArchRCells', X)
}

update_B_cpp <- function(A, B, K, it, t = 0L, verbose = TRUE) {
    .Call('_ArchRCells_update_B_cpp', PACKAGE = 'ArchRCells', A, B, K, it, t, verbose)
}

update_B_cpp_sp <- function(A, B, K, it, t = 0L, verbose = TRUE) {
    .Call('_ArchRCells_update_B_cpp_sp', PACKAGE = 'ArchRCells', A, B, K, it, t, verbose)
}

initialize_A_cpp <- function(nr, nc) {
    .Call('_ArchRCells_initialize_A_cpp', PACKAGE = 'ArchRCells', nr, nc)
}

initialize_A_idx <- function(t1, t2, verbose = TRUE) {
    .Call('_ArchRCells_initialize_A_idx', PACKAGE = 'ArchRCells', t1, t2, verbose)
}

update_A_cpp <- function(A, B, K, it, t = 0L, verbose = TRUE) {
    .Call('_ArchRCells_update_A_cpp', PACKAGE = 'ArchRCells', A, B, K, it, t, verbose)
}

update_A_cpp_sp <- function(A, B, K, it, t = 0L, verbose = TRUE) {
    .Call('_ArchRCells_update_A_cpp_sp', PACKAGE = 'ArchRCells', A, B, K, it, t, verbose)
}

mat_mult_dens_dens_cpp <- function(A, B) {
    .Call('_ArchRCells_mat_mult_dens_dens_cpp', PACKAGE = 'ArchRCells', A, B)
}

mat_mult_dens_sp_cpp <- function(A, B) {
    .Call('_ArchRCells_mat_mult_dens_sp_cpp', PACKAGE = 'ArchRCells', A, B)
}

mat_mult_sp_dens_cpp <- function(A, B) {
    .Call('_ArchRCells_mat_mult_sp_dens_cpp', PACKAGE = 'ArchRCells', A, B)
}

mat_mult_sp_sp_cpp <- function(A, B) {
    .Call('_ArchRCells_mat_mult_sp_sp_cpp', PACKAGE = 'ArchRCells', A, B)
}

determine_waypoints_cpp <- function(v, idx, N, it, nc, verbose) {
    .Call('_ArchRCells_determine_waypoints_cpp', PACKAGE = 'ArchRCells', v, idx, N, it, nc, verbose)
}

